const decodeHTMLEntities = text => {
  const entities = {
    '&amp;': '&',
    '&lt;': '<',
    '&gt;': '>',
    '&quot;': '"',
    '&#039;': "'",
    '&uuml;': 'ü',
    '&eacute;': 'é',
    '&ouml;': 'ö',
    '&auml;': 'ä',
    '&aring;': 'å',
    '&Agrave;': 'À',
    '&Aacute;': 'Á',
    '&Acirc;': 'Â',
    '&Atilde;': 'Ã',
    '&Auml;': 'Ä',
    '&Aring;': 'Å',
    '&agrave;': 'à',
    '&aacute;': 'á',
    '&acirc;': 'â',
    '&atilde;': 'ã',
    '&AElig;': 'Æ',
    '&aelig;': 'æ',
    '&szlig;': 'ß',
    '&Ccedil;': 'Ç',
    '&ccedil;': 'ç',
    '&Egrave;': 'È',
    '&Eacute;': 'É',
    '&Ecirc;': 'Ê',
    '&Euml;': 'Ë',
    '&egrave;': 'è',
    '&ecirc;': 'ê',
    '&euml;': 'ë',
    '&#131;': 'ƒ',
    '&Igrave;': 'Ì',
    '&Iacute;': 'Í',
    '&Icirc;': 'Î',
    '&Iuml;': 'Ï',
    '&igrave;': 'ì',
    '&iacute;': 'í',
    '&icirc;': 'î',
    '&iuml;': 'ï',
    '&Ntilde;': 'Ñ',
    '&ntilde;': 'ñ',
    '&Ograve;': 'Ò',
    '&Oacute;': 'Ó',
    '&Ocirc;': 'Ô',
    '&Otilde;': 'Õ',
    '&Ouml;': 'Ö',
    '&ograve;': 'ò',
    '&oacute;': 'ó',
    '&ocirc;': 'ô',
    '&otilde;': 'õ',
    '&Oslash;': 'Ø',
    '&oslash;': 'ø',
    '&#140;': 'Œ',
    '&#156;': 'œ',
    '&#138;': 'Š',
    '&#154;': 'š',
    '&Ugrave;': 'Ù',
    '&Uacute;': 'Ú',
    '&Ucirc;': 'Û',
    '&Uuml;': 'Ü',
    '&ugrave;': 'ù',
    '&uacute;': 'ú',
    '&ucirc;': 'û',
    '&#181;': 'µ',
    '&#215;': '×',
    '&Yacute;': 'Ý',
    '&#159;': 'Ÿ',
    '&yacute;': 'ý',
    '&yuml;': 'ÿ',
    '&#176;': '°',
    '&#134;': '†',
    '&#135;': '‡',
    '&#177;': '±',
    '&#171;': '«',
    '&#187;': '»',
    '&#191;': '¿',
    '&#161;': '¡',
    '&#183;': '·',
    '&#149;': '•',
    '&#153;': '™',
    '&copy;': '©',
    '&reg;': '®',
    '&#167;': '§',
    '&#182;': '¶',
    '&rsquo;': '’',
    '&ldquo;': '“ ”',
    '&rdquo;': '“ ”',
  }

  return text.replace(
    /&(amp|lt|gt|quot|#039|uuml|eacute|ouml|auml|aring|Agrave|Aacute|Acirc|Atilde|Auml|Aring|agrave|aacute|acirc|atilde|AElig|aelig|szlig|Ccedil|ccedil|Egrave|Eacute|Ecirc|Euml|egrave|ecirc|euml|#131|Igrave|Iacute|Icirc|Iuml|igrave|iacute|icirc|iuml|Ntilde|ntilde|Ograve|Oacute|Ocirc|Otilde|Ouml|ograve|oacute|ocirc|otilde|Oslash|oslash|#140|#156|#138|#154|Ugrave|Uacute|Ucirc|Uuml|ugrave|uacute|ucirc|#181|#215|Yacute|#159|yacute|yuml|#176|#134|#135|#177|#171|#187|#191|#161|#183|#149|#153|copy|reg|#167|#182|rsquo|ldquo|rdquo);/g,
    match => entities[match]
  )
}

export default decodeHTMLEntities
